//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Manager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_HR_ManagerContext : DbContext
    {
        public DB_HR_ManagerContext()
            : base("name=DB_HR_ManagerContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_HR_Admin> TBL_HR_Admin { get; set; }
        public virtual DbSet<TBL_HR_Employee> TBL_HR_Employee { get; set; }
        public virtual DbSet<TBL_HR_Message> TBL_HR_Message { get; set; }
        public virtual DbSet<TBL_HR_Department> TBL_HR_Department { get; set; }
    }
}
