//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HR_Admin
    {
        public string AdminUserName { get; set; }
        public long AdminMobileNumber { get; set; }
        public string AdminEmail { get; set; }
    }
}
